In [1]:
import torch

In [2]:
import sys

sys.path.append('InsightFace_Pytorch/')

In [4]:
import cv2

In [7]:
from dataset.Dataset import FaceEmbed


ds = FaceEmbed(['dataset/CelebAMask-HQ/CelebA-HQ-img/'])

import torch

DS = torch.utils.data.DataLoader(ds)
i =0
for res in DS:
    
    img_1 = res[0].numpy()[0].transpose(1, 2, 0)#.shape
    img_2 = res[1].numpy()[0].transpose(1, 2, 0)

    cv2.imshow('test_0', img_1)
    cv2.waitKey()
    
    cv2.imshow('test', img_2)
    cv2.waitKey()
    
    
    print(res[2])
    if i == 5:
        break
    i += 1

X_s = res[0]

tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])


In [73]:
res[0]

tensor([[[[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          ...,
          [-0.7098, -0.6549, -0.6471,  ..., -0.5059, -0.4510, -0.5216],
          [-0.8039, -0.8275, -0.8196,  ..., -0.6549, -0.6078, -0.6157],
          [-0.7333, -0.9922, -1.0000,  ..., -0.5529, -0.6235, -0.6235]],

         [[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          ...,
          [-0.4902, -0.4353, -0.4196,  ..., -0.2706, -0.2314, -0.2941],
          [-0.5843, -0.6078, -0.6000,  ..., -0.3804, -0.3490, -0.3412],
          [-0.5059, -0.8588, -0.9373,  ..., -0.2392, -0.3098, -0.3098]],

         [[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  

In [74]:
res[2].shape

torch.Size([1])

In [75]:
from PIL import Image

In [78]:
import cv2

In [62]:
Image.fromarray(img_1)

TypeError: Cannot handle this data type: (1, 1, 1024), <f4

In [22]:
from InsightFace_Pytorch.model import Backbone, Arcface, MobileFaceNet, Am_softmax, l2_norm

arcface = Backbone(50, 0.6, 'ir_se')

arcface.eval()

arcface.load_state_dict(torch.load('./InsightFace_Pytorch/model_ir_se50.pth', map_location='cpu'), strict=False)

In [26]:
import torch.nn.functional as F

In [28]:
dummy_input = F.interpolate(X_s[:, :, 19:237, 19:237], [112, 112], mode='bilinear', align_corners=True)

In [29]:
dummy_input.shape

torch.Size([1, 3, 112, 112])

In [39]:
with torch.no_grad():
    out_load_1 = arcface(dummy_input)